openapi: 3.1.0
info:
  title: Task Api
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://task-api-46nq.onrender.com/
    description: Production server on render
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
